services:
  rabbitmq:
    container_name: rabbitmq_container
    image: rabbitmq:3.13-rc-management-alpine
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: myuser
      RABBITMQ_DEFAULT_PASS: mypassword
    ports:
      - "5672:5672"
      - "15672:15672"

  gateway:
    container_name: gateway_container
    build:
      context: ../api-gateway
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "3000:3000"
    env_file: ../api-gateway/configs/.env
    environment:
      ENABLE_APM: "0"
      LOG_LEVEL: debug
      NODE_ENV: development
      PORT: "3000"
      COOKIE_SECRET_KEY_ONE: "48a9c9a7bd58fff6a243d45fdf5dc31b"
      COOKIE_SECRET_KEY_TWO: "9309de3ec71d5c4920b855d0ceb3b477"
      CLIENT_URL: "XXXX"
      RABBITMQ_ENDPOINT: "amqp://localhost"
      AUTH_SERVICE_URL: "http://auth:3001"
      TEACHER_SERVICE_URL: "http://localhost:3002"
      STUDENT_SERVICE_URL: "http://localhost:3003"
      USER_SERVICE_URL: "http://localhost:3004"
      NOTIFICATION_SERVICE_URL: "http://localhost:3005"

  auth:
    container_name: auth
    build:
      context: ../auth
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "3001:3001"
    env_file: ../auth/configs/.env
    environment:
      NODE_ENV: development
      PORT: "3001"
      ROUTE: "/api/v1"
      MONGODB_URL: "mongodb+srv://learnwithkru:gT5jqfgZyQ8UmCNn@learnwithkru.elxl0wh.mongodb.net/auth"
      LOG_LEVEL: debug
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: "587"
      SMTP_APIKEY_PUBLIC: learnwithkru@gmail.com
      SMTP_APIKEY_PRIVATE: "wqfj ktkw mbrc hmdr"
      GOOGLE_CLIENT_ID: "184001752771-hnj5akcqg536da50k9ga5n4e9n3jcgbc.apps.googleusercontent.com"
      GOOGLE_CLIENT_SECRET: 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
      GOOGLE_REDIRECT_URI: "http://localhost:3000/v1/auth/google/callback"
      FACEBOOK_APP_ID: "810121707191447"
      FACEBOOK_APP_SECRET: "83f6227d99462875f27df4198f87870f"
      FACEBOOK_REDIRECT_URI: "http://localhost:3000/v1/auth/facebook/callback"
      SECRET_KEY: "learnwithkru@$4422"
      API_GATEWAY: "http://localhost:3000"
      JWT_EXPIRES_IN: "30d"
      RABBITMQ_ENDPOINT: "amqp://myuser:mypassword@rabbitmq_container:5672"
      USER_SERVICE: "http://localhost:3004/v1/users"

  user:
    container_name: user_container
    build:
      context: ../user
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "3004:3004"
    env_file: ../user/configs/.env
    environment:
      NODE_ENV: development
      PORT: 3003
      ROUTE: /api/v1
      #auth service url
      AUTH_SERVICE_GET: http://localhost:3001/v1/auth/user
      # Database Service
      MONGODB_URL: mongodb+srv://learnwithkru:gT5jqfgZyQ8UmCNn@learnwithkru.elxl0wh.mongodb.net/user  
      # Log Service
      LOG_LEVEL: debug
      API_GATEWAY: http://localhost:3000

  notification:
    container_name: notification_container
    build:
      context: ../notification
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "3005:3005"
    env_file: ../notification/configs/.env
    environment:
      ENABLE_APM: "0"
      LOG_LEVEL: debug
      NODE_ENV: development
      PORT: "3005"
      CLIENT_URL: "http://localhost:8000"
      RABBITMQ_ENDPOINT: "amqp://myuser:mypassword@rabbitmq_container:5672"
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: "587"
      SENDER_EMAIL: learnwithkru@gmail.com
      SENDER_EMAIL_PASSWORD: "wqfj ktkw mbrc hmdr"
    depends_on:
      - rabbitmq
  student:
    container_name: student_container
    build:
      context: ../student
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "3003:3003"
    env_file: ../student/configs/.env
    environment:
      NODE_ENV: development
      PORT: 3003     
      ROUTE: /api/v1     
      #auth service url
      AUTH_SERVICE_GET: http://localhost:3001/v1/auth/user   
      # Database Service
      MONGODB_URL: mongodb+srv://learnwithkru:gT5jqfgZyQ8UmCNn@learnwithkru.elxl0wh.mongodb.net/student    
      # Log Service
      LOG_LEVEL: debug  
      JWT_EXPIRES_IN: 30d 
      COOKIE_SECRET_KEY_ONE: 48a9c9a7bd58fff6a243d45fdf5dc31b
      COOKIE_SECRET_KEY_TWO: 9309de3ec71d5c4920b855d0ceb3b477

  teacher:
    container_name: teacher_container
    build:
      context: ../teacher
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "3002:3002"
    env_file: ../teacher/configs/.env
    environment:
      NODE_ENV: development
      PORT: 3002
      ROUTE: /api/v1
      # Database Service
      MONGODB_URL: mongodb+srv://learnwithkru:gT5jqfgZyQ8UmCNn@learnwithkru.elxl0wh.mongodb.net/teacher
      # Log Service
      LOG_LEVEL: debug
